version: '3.6'

services:
  php:
    container_name: infuse_media_php
    build:
      dockerfile: docker/php/Dockerfile
      context: .
    environment:
#      DB_HOST: 192.168.100.9
      DB_HOST: database
      DB_NAME: infuse_media
      DB_USER: root
      DB_PASS: ''
    volumes:
      - ./:/opt/app/

  nginx:
    container_name: infuse_media_nginx
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
    ports:
      - 8080:80
    volumes:
      - ./public:/opt/app/public

  database:
    image: mysql:8
    container_name: infuse_media_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: infuse_media
    ports:
      - ${DATABASE_PORT:-3306}:3306
    volumes:
      - database_data:/var/lib/mysql
    command: ['--default-authentication-plugin=mysql_native_password', '--net-read-timeout=90', '--net-write-timeout=90']

volumes:
  database_data: ~

networks:
  app: ~
